import AuditLogPanel from "@/components/AuditLogPanel";
import CompanySetupDialog from "@/components/CompanySetupDialog";
import CompanySettingsPanel from "@/components/CompanySettingsPanel";
import UserManagementPanel from "@/components/UserManagementPanel";
import CommercialDocumentsPanel from "@/components/CommercialDocumentsPanel";
import AccountingRegistryPanel from "@/components/AccountingRegistryPanel";
import OperationalReportsPanel from "@/components/OperationalReportsPanel";
import MasterDataPanel from "@/components/MasterDataPanel";
import OperationalDataPanel from "@/components/OperationalDataPanel";
import InventoryPanel from "@/components/InventoryPanel";
import CashDraftsPanel from "@/components/CashDraftsPanel";
import ApprovalGatePanel from "@/components/ApprovalGatePanel";
import ReferenceDocumentPreview from "@/components/ReferenceDocumentPreview";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BarChart3, BookOpenCheck, Boxes, BriefcaseBusiness, Building2, CheckCircle2, CircleDollarSign, CircleUserRound, ClipboardList, FileClock, FileText, FolderKanban, FolderLock, Inbox, Landmark, PackageSearch, ReceiptText, ScrollText, Settings2, ShieldCheck, ShoppingCart, Truck, UsersRound, WalletCards } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export type ModuleKey = "sales" | "purchases" | "inventory" | "cash" | "operations" | "accounting" | "reports" | "projects" | "assets" | "hr" | "audit" | "administration" | "settings";

const modulePermission = {
  sales: "sales.create", purchases: "purchases.create", inventory: "inventory.create", cash: "accounting.read", accounting: "accounting.read", reports: "reports.read", audit: "audit.read", administration: "administration.manage", assets: "administration.manage", hr: "administration.manage", settings: "administration.manage",
} as const;
const masterDataModule = { sales: "customer", purchases: "supplier", inventory: "item" } as const;
const operationalDataModule = { cash: "cash", projects: "projects", assets: "assets", hr: "hr" } as const;

type ModuleDefinition = { eyebrow: string; title: string; description: string; icon: LucideIcon; accent: string; steps: string[]; recordsTitle: string; recordsDescription: string; controls: { label: string; description: string; icon: LucideIcon }[]; actionLabel?: string; gate?: boolean };

const definitions: Record<ModuleKey, ModuleDefinition> = {
  sales: { eyebrow: "الدورة التجارية", title: "المبيعات والعملاء", description: "إدارة العملاء والعروض وأوامر البيع والفواتير والتحصيل ضمن دورة مستندات قابلة للتدقيق.", icon: ReceiptText, accent: "#3399ff", steps: ["العميل", "العرض", "أمر البيع", "الفاتورة والتحصيل"], recordsTitle: "لا توجد مستندات مبيعات بعد", recordsDescription: "أضف العملاء أولًا، ثم أنشئ المستندات من خلال إجراءات مصادق عليها.", controls: [{ label: "العملاء", description: "ملف قانوني وائتماني لكل عميل.", icon: UsersRound }, { label: "العروض والفواتير", description: "دورة واضحة من المسودة إلى الاعتماد.", icon: FileText }, { label: "التحصيل", description: "ربط لاحق بالنقد والذمم ضمن الحوكمة.", icon: CheckCircle2 }], actionLabel: "فتح سجلات العملاء" },
  purchases: { eyebrow: "سلسلة التوريد", title: "المشتريات والموردون", description: "طلبات الشراء والأوامر والاستلام والفواتير الواردة، مع فصل التحكم التشغيلي عن الالتزام المالي.", icon: ShoppingCart, accent: "#e09a2e", steps: ["المورد", "طلب الشراء", "أمر الشراء", "الاستلام والفاتورة"], recordsTitle: "لا توجد مستندات مشتريات بعد", recordsDescription: "ابدأ بتسجيل الموردين المعتمدين قبل إنشاء أوامر الشراء.", controls: [{ label: "الموردون", description: "حفظ الملف القانوني والضريبي وبيانات التواصل.", icon: UsersRound }, { label: "أوامر الشراء", description: "تتبع الالتزام قبل الاستلام.", icon: ClipboardList }, { label: "المطابقة", description: "تهيئة لمسار مستند–استلام–فاتورة.", icon: BookOpenCheck }], actionLabel: "فتح سجلات الموردين" },
  inventory: { eyebrow: "الرقابة المادية", title: "المخزون والوقود", description: "الأصناف والمستودعات والخزانات والتحويلات. لا يُعتمد رصيد إلا من حركة موثقة المصدر والوجهة.", icon: Boxes, accent: "#27b8a4", steps: ["الصنف", "الموقع", "الحركة", "الجرد والمطابقة"], recordsTitle: "لا توجد حركات مخزون مسجلة", recordsDescription: "عرّف الأصناف والمواقع قبل بدء إدخال أي حركة مخزون.", controls: [{ label: "الأصناف", description: "وحدات قياس وأنواع مخزون ووقود وخدمات.", icon: PackageSearch }, { label: "المواقع", description: "مستودعات وخزانات وناقلات بسعة تشغيلية.", icon: Boxes }, { label: "الحركات", description: "تحقق من الكمية والمصدر والوجهة عند النقل.", icon: ScrollText }], actionLabel: "فتح سجل الأصناف" },
  cash: { eyebrow: "الخزينة", title: "النقد والبنوك", description: "مساحة محكومة لإدارة الحسابات البنكية والصناديق والمطابقات دون تنفيذ قيود أو تسويات مالية قبل الاعتماد.", icon: WalletCards, accent: "#30b875", steps: ["الحساب البنكي", "الصندوق", "الحركة", "المطابقة"], recordsTitle: "لا توجد حسابات أو حركات نقدية", recordsDescription: "يتطلب هذا المسار تعريف الشركة وسياسات النقد واعتماد دور مالي مناسب.", controls: [{ label: "الحسابات البنكية", description: "تعريف الحسابات وفق الشركة والعملة والسياسة.", icon: Landmark }, { label: "الصناديق", description: "فصل أمين الصندوق والمراجع في الإعدادات المعتمدة.", icon: CircleDollarSign }, { label: "المطابقة", description: "لا تُفعّل إلا مع كشف موثق وإجراء معتمد.", icon: CheckCircle2 }], gate: true },
  operations: { eyebrow: "العمليات الميدانية", title: "العمليات والتسليم", description: "ربط المركبات والسائقين والرحلات والتسليمات والاستثناءات بسجل عمليات قابل للمراجعة.", icon: Truck, accent: "#5a9cf4", steps: ["التجهيز", "التعيين", "الرحلة", "التسليم"], recordsTitle: "لا توجد رحلات تشغيلية", recordsDescription: "تظهر حالات الرحلات والتسليمات عند إعداد المواقع وفرق التشغيل.", controls: [{ label: "المركبات", description: "سجل للمورد المتحرك والمسؤول التشغيلي.", icon: Truck }, { label: "التسليمات", description: "توثيق التنفيذ وربطه بالمستند المصدر.", icon: ReceiptText }, { label: "الاستثناءات", description: "مسار مخصص للحالات الميدانية غير المطابقة.", icon: FileClock }] },
  accounting: { eyebrow: "الحوكمة المالية", title: "المحاسبة العامة", description: "دليل الحسابات والفترات والقيود والدفتر العام متاحة كبنية محكومة، لكن الترحيل الفعلي محجوب حتى اكتمال بوابات الجاهزية.", icon: Landmark, accent: "#ff784c", steps: ["دليل الحسابات", "الفترات", "قواعد الربط", "الترحيل المحكوم"], recordsTitle: "الترحيل المالي غير مفعّل", recordsDescription: "لا تُنشأ قيود يومية أو ميزان مراجعة رسمي قبل اعتماد السياسة والصلاحيات وفصل الواجبات.", controls: [{ label: "دليل الحسابات", description: "إصدارات وتواريخ سريان مع منع الترحيل افتراضيًا.", icon: BookOpenCheck }, { label: "قيود اليومية", description: "تحقق برمجي من سلامة المدين والدائن.", icon: ReceiptText }, { label: "الفصل بين الواجبات", description: "فصل الإنشاء والمراجعة والترحيل بسلطات مختلفة.", icon: FolderLock }], gate: true },
  reports: { eyebrow: "التحليل التنفيذي", title: "التقارير والتحليلات", description: "مساحة التقارير المالية والتشغيلية. لا تُصدر القوائم الرسمية إلا من بيانات مرحّلة ومصالحة معتمدة.", icon: BarChart3, accent: "#a56df3", steps: ["مصدر موثوق", "اعتماد", "مصالحات", "إصدار التقرير"], recordsTitle: "لا توجد بيانات معتمدة لإصدار التقارير", recordsDescription: "ستظهر التقارير عندما تكتمل سلسلة البيانات والحوكمة المطلوبة.", controls: [{ label: "التقارير المالية", description: "الربح والخسارة والميزانية والتدفقات ضمن بوابة الجاهزية.", icon: Landmark }, { label: "تحليلات تشغيلية", description: "اتجاهات المبيعات والمخزون والعمليات من البيانات المسجلة.", icon: BarChart3 }, { label: "التصدير", description: "كل تصدير مستقبلي يسجل ضمن أثر تدقيق واضح.", icon: FileText }], gate: true },
  projects: { eyebrow: "إدارة المشروعات", title: "المشاريع والعقود", description: "مركز لإدارة المشاريع والعقود والمراحل والتكاليف مع إبقاء المعالجة المالية الرسمية ضمن بوابتها المستقلة.", icon: FolderKanban, accent: "#4b8dd8", steps: ["المشروع", "العقد", "الموازنة", "المتابعة"], recordsTitle: "لا توجد مشاريع أو عقود", recordsDescription: "ابدأ بتعريف نطاق المشروع والمسؤول وصلاحيات الوصول.", controls: [{ label: "المشروعات", description: "هيكل مشروع ومراحل ومسؤوليات واضحة.", icon: FolderKanban }, { label: "العقود", description: "ربط لاحق بالعروض والمبيعات والمشتريات.", icon: FileText }, { label: "التكلفة", description: "تتطلب سياسة تكلفة ومصدرًا معتمدًا.", icon: CircleDollarSign }] },
  assets: { eyebrow: "إدارة الأصول", title: "الأصول الثابتة", description: "سجل موحّد للأصول ودورة الاستحواذ والتصنيف والاستهلاك ضمن سياسات معتمدة قابلة للمراجعة.", icon: Building2, accent: "#45a7bd", steps: ["الفئة", "الأصل", "الموقع", "السياسة"], recordsTitle: "لا توجد أصول ثابتة مسجلة", recordsDescription: "يتطلب التسجيل اعتماد سياسة الأصول، ولا يُحتسب الاستهلاك محاسبيًا في هذه المرحلة.", controls: [{ label: "سجل الأصول", description: "معرف أصل وحيازة وموقع ومسؤول.", icon: Building2 }, { label: "الفئات", description: "تصنيف موحد لإتاحة التقارير لاحقًا.", icon: ClipboardList }, { label: "الاستهلاك", description: "محجوب إلى اعتماد السياسة والترحيل.", icon: FolderLock }], gate: true },
  hr: { eyebrow: "رأس المال البشري", title: "الموارد البشرية", description: "إدارة الموظفين والبنية التنظيمية ودورات العمل والصلاحيات مع منع أي معالجة رواتب فعلية قبل اعتمادها.", icon: UsersRound, accent: "#da7d9b", steps: ["الموظف", "الهيكل", "الدور", "دورة العمل"], recordsTitle: "لا توجد سجلات موظفين", recordsDescription: "ابدأ بالهيكل التنظيمي والسياسات قبل إدخال بيانات الموارد البشرية.", controls: [{ label: "الموظفون", description: "سجل هوية وظيفية لا يخلط مع بيانات الدخول.", icon: UsersRound }, { label: "الهيكل", description: "إدارات ومراكز مسؤولية واضحة.", icon: BriefcaseBusiness }, { label: "الرواتب", description: "محجوبة حتى اعتماد السياسة والدليل.", icon: FolderLock }], gate: true },
  audit: { eyebrow: "الأثر والشفافية", title: "الرقابة والتدقيق", description: "سجل أحداث ملحق فقط، وتتبّع للفاعل والوقت والكيان وسياق التغيير ضمن نطاق الشركة والصلاحية.", icon: ScrollText, accent: "#e1ad54", steps: ["هوية", "طلب خادمي", "حدث تدقيق", "مراجعة الدليل"], recordsTitle: "لم تُسجّل أحداث تدقيق بعد", recordsDescription: "تظهر الأحداث عند تنفيذ عمليات خادمية مصادق عليها.", controls: [{ label: "الأحداث", description: "إنشاء وتعديل وإلغاء واعتماد وتصدير.", icon: ScrollText }, { label: "المسؤول", description: "ربط الحدث بمستخدم مصادق عليه.", icon: CircleUserRound }, { label: "الدليل", description: "سياق الحدث دون كشف الحقول الحساسة.", icon: ShieldCheck }] },
  administration: { eyebrow: "إدارة المؤسسة", title: "الإدارة والصلاحيات", description: "الشركة والفروع والمستخدمون والأدوار ونطاقات البيانات. تتحقق الصلاحيات على الخادم قبل أي عملية.", icon: ShieldCheck, accent: "#52b2ff", steps: ["الشركة", "الفروع", "الدور", "النطاق"], recordsTitle: "لم تُهيأ الشركة أو نطاقات البيانات بعد", recordsDescription: "ابدأ بإنشاء الشركة، ثم عرّف الفروع والمستخدمين قبل تشغيل المستندات.", controls: [{ label: "الشركة والفروع", description: "فصل الكيان القانوني والوحدات التشغيلية.", icon: Building2 }, { label: "الأدوار", description: "مدير، مدير نظام، محاسب، مستخدم.", icon: UsersRound }, { label: "نطاق البيانات", description: "شركة أو فرع أو مهام مخصصة.", icon: FolderLock }], actionLabel: "تهيئة الشركة" },
  settings: { eyebrow: "إعداد النظام", title: "الإعدادات والسياسات", description: "إعدادات الشركة والعملة والسياسات وضوابط النشر. التغيير الفعلي محكوم بصلاحيات الإدارة وسجل تدقيق.", icon: Settings2, accent: "#8099bc", steps: ["التفضيلات", "السياسات", "الإشعارات", "التحقق"], recordsTitle: "لا توجد إعدادات تشغيلية إضافية", recordsDescription: "تظهر الإعدادات القابلة للتعديل بعد اكتمال الشركة وتحديد صلاحية مدير النظام.", controls: [{ label: "السياسات", description: "سنة مالية وعملات ومسارات اعتماد.", icon: BookOpenCheck }, { label: "الحماية", description: "الجلسات والأدوار والحدود التشغيلية.", icon: ShieldCheck }, { label: "التكاملات", description: "اتصال Supabase قراءة فقط حتى اعتماد النطاق.", icon: Settings2 }] },
};

export default function ModulePage({ moduleKey }: { moduleKey: ModuleKey }) {
  const module = definitions[moduleKey];
  const Icon = module.icon;
  const [, setLocation] = useLocation();
  const [setupOpen, setSetupOpen] = useState(false);
  const { isAuthenticated } = useAuth();
  const requestedPermission = modulePermission[moduleKey as keyof typeof modulePermission];
  const masterDataKind = masterDataModule[moduleKey as keyof typeof masterDataModule];
  const operationalDataKind = operationalDataModule[moduleKey as keyof typeof operationalDataModule];
  const access = trpc.erp.may.useQuery({ permission: requestedPermission ?? "dashboard.read" }, { enabled: isAuthenticated && Boolean(requestedPermission) });
  const accessDenied = Boolean(requestedPermission && access.data && !access.data.allowed);
  const action = () => moduleKey === "administration" ? setSetupOpen(true) : masterDataKind ? undefined : setLocation("/administration");

  return <div className="space-y-4">
    <section className="relative overflow-hidden rounded-2xl border border-[#214c6c] bg-[linear-gradient(110deg,#0d304a,#092239_56%,#102f49)] px-5 py-6 shadow-[0_20px_48px_rgba(0,0,0,0.2)] sm:px-6">
      <div className="absolute inset-0 opacity-60 [background-image:radial-gradient(circle_at_90%_5%,rgba(86,183,255,0.16),transparent_25%),linear-gradient(135deg,rgba(255,255,255,0.04)_1px,transparent_1px)] [background-size:auto,18px_18px]" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="mb-3 flex items-center gap-2 text-[11px] font-bold" style={{ color: module.accent }}><Icon className="h-4 w-4" />{module.eyebrow}</div><h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">{module.title}</h2><p className="mt-3 text-sm leading-7 text-[#a2bdd0]">{module.description}</p></div>{module.actionLabel ? <Button onClick={action} disabled={accessDenied} className="h-10 rounded-lg bg-[#1e7fc5] px-4 text-xs text-white hover:bg-[#196eab] disabled:opacity-60">{module.actionLabel}</Button> : <div className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs ${module.gate ? "border-[#754037] bg-[#3b2528] text-[#ffb0a3]" : "border-[#28516e] bg-[#0c2b44] text-[#a5cdf0]"}`}><FolderLock className="h-4 w-4" />{module.gate ? "إجراء مالي محجوب حوكميًا" : "مساحة عمل قيد التهيئة"}</div>}</div>
    </section>
    {isAuthenticated && requestedPermission && access.isLoading ? <div className="flex items-center gap-2 rounded-xl border border-[#214a68] bg-[#0a2941] px-4 py-3 text-sm text-[#9fc5df]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#57b9ff]" />جارٍ التحقق من نطاق الصلاحية…</div> : null}
    {accessDenied ? <div className="flex items-start gap-3 rounded-xl border border-[#683c42] bg-[#301f2a] px-4 py-3.5 text-sm text-[#ffbeb5]"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" /><div><p className="font-bold">وصول العرض فقط</p><p className="mt-1 text-xs leading-5 text-[#e5a39c]">لا يملك دورك الحالي صلاحية إدارة هذه الوحدة. تتحقق الصلاحيات خادميًا قبل التنفيذ.</p></div></div> : null}
    {!isAuthenticated ? <div className="flex items-start gap-3 rounded-xl border border-[#214a68] bg-[#0a2941] px-4 py-3.5 text-sm text-[#b4d4e9]"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#64c3ff]" /><div><p className="font-bold">وضع الاستعراض</p><p className="mt-1 text-xs leading-5 text-[#82a2b9]">تسجيل الدخول مطلوب قبل قراءة أو إنشاء أي بيانات مؤسسية.</p></div></div> : null}
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{module.steps.map((step, index) => <div key={step} className="relative overflow-hidden rounded-xl border border-[#1c4563] bg-[#09253d] p-4"><span className="absolute left-3 top-2 font-serif text-3xl font-bold text-[#163b58]">0{index + 1}</span><p className="relative mt-7 text-sm font-bold text-[#dbeafa]">{step}</p><p className="relative mt-1 text-[10px] text-[#7899b0]">خطوة منظمة ضمن دورة العمل</p></div>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.55fr_0.85fr]">{moduleKey === "audit" ? <AuditLogPanel accessDenied={accessDenied} /> : moduleKey === "settings" ? <CompanySettingsPanel accessDenied={accessDenied} accessResolved={!access.isLoading} /> : moduleKey === "administration" ? <div className="space-y-4"><UserManagementPanel accessDenied={accessDenied} accessResolved={!access.isLoading} /><ApprovalGatePanel accessDenied={accessDenied} /></div> : moduleKey === "sales" ? <CommercialDocumentsPanel area="sales" accessDenied={accessDenied} accessResolved={!access.isLoading} /> : moduleKey === "purchases" ? <CommercialDocumentsPanel area="purchases" accessDenied={accessDenied} accessResolved={!access.isLoading} /> : moduleKey === "inventory" ? <InventoryPanel accessDenied={accessDenied} accessResolved={!access.isLoading} /> : moduleKey === "cash" ? <div className="space-y-4"><OperationalDataPanel kind="cash" accessDenied={accessDenied} accessResolved={!access.isLoading} /><CashDraftsPanel accessDenied={accessDenied} accessResolved={!access.isLoading} /><ReferenceDocumentPreview kind="receipt" compact /></div> : moduleKey === "accounting" ? <AccountingRegistryPanel accessDenied={accessDenied} accessResolved={!access.isLoading} /> : moduleKey === "reports" ? <OperationalReportsPanel accessDenied={accessDenied} accessResolved={!access.isLoading} /> : masterDataKind ? <MasterDataPanel kind={masterDataKind} accessDenied={accessDenied} accessResolved={!access.isLoading} /> : operationalDataKind ? <OperationalDataPanel kind={operationalDataKind} accessDenied={accessDenied} accessResolved={!access.isLoading} /> : <div className="rounded-2xl border border-[#1c4563] bg-[#092238] shadow-[0_18px_42px_rgba(0,0,0,0.15)]"><div className="flex items-center justify-between border-b border-[#193f5d] px-5 py-4"><div><h3 className="text-sm font-bold text-[#e6f2fc]">سجل الوحدة</h3><p className="mt-1 text-[10px] text-[#7796ab]">بيانات حقيقية فقط ضمن نطاق الصلاحية</p></div><span className="rounded-md border border-[#294e6b] bg-[#0c2c45] px-2 py-1 text-[10px] text-[#9dc5e3]">قيد التهيئة</span></div><div className="flex min-h-[270px] flex-col items-center justify-center px-6 py-10 text-center"><div className="grid h-12 w-12 place-items-center rounded-xl border border-[#27506e] bg-[#0c2c45] text-[#70c4ff]"><Inbox className="h-5 w-5" /></div><h4 className="mt-4 text-base font-bold text-[#d8eaf7]">{module.recordsTitle}</h4><p className="mt-2 max-w-md text-sm leading-6 text-[#7f9eb3]">{module.recordsDescription}</p></div></div>}
      <div className="rounded-2xl border border-[#214e6f] bg-[linear-gradient(145deg,#0e3450,#0a2136)] p-5 shadow-[0_18px_42px_rgba(0,0,0,0.15)]"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#164563] text-[#7cd0ff]"><ShieldCheck className="h-5 w-5" /></div><div><h3 className="text-sm font-bold text-[#ecf6ff]">ضابط التنفيذ</h3><p className="mt-1 text-[10px] text-[#91b2c9]">قبل إنشاء أي أثر تشغيلي أو مالي</p></div></div><div className="mt-5 space-y-2.5">{module.controls.map((control) => { const ControlIcon = control.icon; return <div key={control.label} className="rounded-xl border border-[#214a67] bg-[#092941] p-3"><div className="flex items-center gap-2 text-xs font-bold text-[#e6f4ff]"><ControlIcon className="h-3.5 w-3.5 text-[#6fc8ff]" />{control.label}</div><p className="mt-1.5 pr-5.5 text-[11px] leading-5 text-[#8dacc2]">{control.description}</p></div>; })}</div></div>
    </section>
    <CompanySetupDialog open={setupOpen} onOpenChange={setSetupOpen} />
  </div>;
}
