import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, CalendarRange, Loader2, LockKeyhole } from "lucide-react";

export default function AccountingRegistryPanel({ accessDenied, accessResolved }: { accessDenied: boolean; accessResolved: boolean }) {
  const { isAuthenticated } = useAuth();
  const enabled = isAuthenticated && accessResolved && !accessDenied;
  const accounts = trpc.erp.accountingRegistry.chartOfAccounts.useQuery(undefined, { enabled, retry: false });
  const periods = trpc.erp.accountingRegistry.periods.useQuery(undefined, { enabled, retry: false });
  const readiness = trpc.erp.financial.readiness.useQuery();
  const setupRequired = Boolean(accounts.error?.message.includes("إكمال تهيئة الشركة") || periods.error?.message.includes("إكمال تهيئة الشركة"));
  return <div className="space-y-4"><div className="rounded-2xl border border-[#6d4639] bg-[#2c2024] px-4 py-3 text-xs leading-6 text-[#ffc0af]"><span className="font-bold">حد الحوكمة:</span> السجل أدناه للقراءة فقط. إنشاء الحسابات والفترات، والقيود، والترحيل تبقى محجوبة حتى تحقق بوابة الجاهزية بالأدلة المطلوبة.</div>{setupRequired ? <RegistryEmpty /> : <div className="grid gap-4 2xl:grid-cols-2"><RegistryCard title="دليل الحسابات" subtitle="إصدار مسجل؛ لا يمنح صلاحية ترحيل" icon={<BookOpenCheck className="h-4 w-4" />} loading={accounts.isLoading} error={accounts.error?.message} empty={!accounts.data?.length}><table className="w-full min-w-[480px] text-right"><thead><tr><th>الرمز</th><th>الحساب</th><th>النوع</th><th>الترحيل</th></tr></thead><tbody>{accounts.data?.map((account) => <tr key={account.id}><td className="font-mono">{account.accountCode}</td><td>{account.name}</td><td>{account.accountType}</td><td><span className="rounded bg-[#342429] px-2 py-1 text-[10px] text-[#efb3a8]">محجوب</span></td></tr>)}</tbody></table></RegistryCard><RegistryCard title="الفترات المحاسبية" subtitle="عرض الحالة فقط" icon={<CalendarRange className="h-4 w-4" />} loading={periods.isLoading} error={periods.error?.message} empty={!periods.data?.length}><table className="w-full min-w-[460px] text-right"><thead><tr><th>الفترة</th><th>من</th><th>إلى</th><th>الحالة</th></tr></thead><tbody>{periods.data?.map((period) => <tr key={period.id}><td className="font-mono">{period.periodCode}</td><td>{new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(period.startsAt))}</td><td>{new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(period.endsAt))}</td><td>{period.status}</td></tr>)}</tbody></table></RegistryCard></div>}<div className="flex items-center gap-3 rounded-xl border border-[#214a67] bg-[#08253c] px-4 py-3 text-[11px] text-[#9fbed2]"><LockKeyhole className="h-4 w-4 shrink-0 text-[#f1b875]" />{readiness.data?.ready ? "تستلزم أي عملية مالية مسار ترحيل مستقل مصادق عليه." : `الترحيل والقوائم الرسمية محجوبان: ${readiness.data?.reason ?? "جارٍ التحقق من الجاهزية"}`}</div></div>;
}

function RegistryCard({ title, subtitle, icon, loading, error, empty, children }: { title: string; subtitle: string; icon: React.ReactNode; loading: boolean; error?: string; empty: boolean; children: React.ReactNode }) { return <div className="overflow-hidden rounded-2xl border border-[#1c4563] bg-[#092238]"><div className="flex items-center gap-2 border-b border-[#193f5d] px-5 py-4 text-[#77caf7]">{icon}<div><h3 className="text-sm font-bold text-[#e6f2fc]">{title}</h3><p className="mt-1 text-[10px] text-[#7899af]">{subtitle}</p></div></div><div className="min-h-[190px] px-5 py-4">{loading ? <div className="flex h-[150px] items-center justify-center gap-2 text-sm text-[#9ab9cf]"><Loader2 className="h-4 w-4 animate-spin" />جارٍ التحميل…</div> : error ? <div className="flex h-[150px] items-center justify-center text-center text-xs text-[#ffb0a5]">{error}</div> : empty ? <div className="flex h-[150px] items-center justify-center text-center text-xs leading-5 text-[#88a8be]">لا توجد سجلات معتمدة للعرض. لا ينشئ هذا المسار بيانات محاسبية.</div> : <div className="overflow-x-auto registry-table">{children}</div>}</div></div>; }

function RegistryEmpty() { return <div className="flex min-h-[280px] flex-col items-center justify-center px-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-xl border border-[#5b4a2e] bg-[#2d261c] text-[#edc56c]"><LockKeyhole className="h-5 w-5" /></div><h4 className="mt-3 text-sm font-bold text-[#f2dfad]">يلزم تهيئة الشركة أولًا</h4><p className="mt-1 max-w-sm text-xs leading-5 text-[#bcae89]">لا يمكن عرض دليل الحسابات أو الفترات قبل ربط المستخدم بنطاق شركة مصادق عليه.</p></div>; }
