import { trpc } from "@/lib/trpc";
import { Ban, CircleAlert, FileLock2, Fingerprint, ShieldCheck } from "lucide-react";

export default function ApprovalGatePanel({ accessDenied }: { accessDenied: boolean }) {
  const readiness = trpc.erp.financial.readiness.useQuery(undefined, { retry: false });
  const gates = readiness.data?.gates ?? [];

  return <section className="rounded-2xl border border-[#6b3c42] bg-[linear-gradient(145deg,#301e29,#211b2a)] shadow-[0_18px_42px_rgba(0,0,0,0.15)]">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#623840] px-5 py-4 sm:px-6"><div><div className="flex items-center gap-2"><h3 className="text-sm font-bold text-[#ffe0da]">بوابة الاعتماد والهوية</h3><span className="rounded-md border border-[#81434b] bg-[#4b2730] px-2 py-1 font-mono text-[9px] font-bold text-[#ffb5a8]">APPROVAL_RECORDING_BLOCKED</span></div><p className="mt-1 text-[10px] leading-5 text-[#dca9a4]">الحالة المعروضة حوكمية؛ لا تُنشأ سجلات اعتماد رسمية أو سلطة ترحيل قبل إثبات هوية المعتمد وسجل الأدلة غير القابل للتعديل.</p></div><Ban className="h-5 w-5 text-[#ff978d]" /></div>
    {accessDenied ? <div className="px-5 py-5 text-sm text-[#f1beb6]">عرض تفاصيل الحوكمة الإدارية مقيّد لدورك الحالي.</div> : <div className="px-5 py-5 sm:px-6"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-[#6a4248] bg-[#271e29] p-4"><Fingerprint className="h-4 w-4 text-[#ffb6a8]" /><h4 className="mt-3 text-xs font-bold text-[#ffe3dc]">هوية معتمد متحقق منها خادميًا</h4><p className="mt-1 text-[11px] leading-5 text-[#d4a8a2]">غير مثبتة كهوية اعتماد مالية مع issuer وaudience وJWKS وصلاحية ونطاق قرار.</p></div><div className="rounded-xl border border-[#6a4248] bg-[#271e29] p-4"><FileLock2 className="h-4 w-4 text-[#ffb6a8]" /><h4 className="mt-3 text-xs font-bold text-[#ffe3dc]">سجل اعتماد وأدلة غير قابل للتعديل</h4><p className="mt-1 text-[11px] leading-5 text-[#d4a8a2]">لا يوجد Approval ID أو Evidence ID أو hash متسلسل خادمي صالح للاعتماد المالي.</p></div><div className="rounded-xl border border-[#6a4248] bg-[#271e29] p-4"><ShieldCheck className="h-4 w-4 text-[#ffb6a8]" /><h4 className="mt-3 text-xs font-bold text-[#ffe3dc]">فصل الواجبات والترحيل</h4><p className="mt-1 text-[11px] leading-5 text-[#d4a8a2]">القرارات التشغيلية الحالية لا تمنح اعتمادًا ماليًا ولا سلطة قيد أو ترحيل.</p></div></div><div className="mt-4 rounded-xl border border-[#75434a] bg-[#281d28] p-4"><div className="flex items-start gap-2"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-[#ffad9d]" /><div><h4 className="text-xs font-bold text-[#ffe5df]">الحد التنفيذي الصريح</h4><p className="mt-1 text-[11px] leading-5 text-[#e2b4ad]">اعتماد مستند المبيعات أو المشتريات هنا قرار تشغيلي فقط. كما أن مسودات القبض والصرف غير مرحلة ولا تغيّر الأرصدة. لا يمكن اعتبار أيٍ منهما توقيعًا أو موافقة مالية رسمية.</p></div></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{gates.map((gate) => <div key={gate.id} className="flex items-center justify-between gap-2 rounded-lg border border-[#543941] bg-[#211c29] px-3 py-2.5"><span className="text-[11px] text-[#edc5bf]"><b className="ml-2 font-mono text-[#ffaf9f]">{gate.id}</b>{gate.label}</span><span className="rounded bg-[#4b2730] px-1.5 py-0.5 text-[9px] font-bold text-[#ffb9ad]">محجوب</span></div>)}</div>{readiness.data ? <p className="mt-3 text-[11px] text-[#dfaea8]">{readiness.data.reason}</p> : <p className="mt-3 text-[11px] text-[#be9895]">جارٍ قراءة حالة بوابات الجاهزية من الخادم…</p>}</div>}
  </section>;
}
