import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BarChart3, Boxes, CircleDollarSign, ClipboardCheck, FileCheck2, FileWarning, History, Loader2, LockKeyhole, UsersRound } from "lucide-react";

const documentStatusLabels: Record<string, string> = { draft: "مسودات", in_review: "قيد المراجعة", approved: "مقبولة تشغيليًا", cancelled: "ملغاة" };
const documentKindLabels: Record<string, string> = { quotation: "عروض السعر", sales_invoice: "فواتير المبيعات", purchase_request: "طلبات الشراء", purchase_order: "أوامر الشراء" };
const movementLabels: Record<string, string> = { in: "إدخال", out: "إخراج", transfer: "تحويل", adjustment: "تسوية" };
const cashDraftKindLabels: Record<string, string> = { receipt: "مسودات قبض", payment: "مسودات صرف" };

function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="rounded-xl border border-[#214a67] bg-[#08253c] p-4"><div className="flex items-center justify-between gap-2"><p className="text-[10px] text-[#86a6bd]">{label}</p><span className="text-[#65b9e9]">{icon}</span></div><p className="mt-2 font-mono text-2xl font-bold text-[#dff1ff]">{value}</p></div>; }
function Breakdown({ title, rows, labels, quantity }: { title: string; rows: { key: string; count: number; quantity?: number }[]; labels: Record<string, string>; quantity?: boolean }) { const max = Math.max(1, ...rows.map((row) => row.count)); return <div className="rounded-xl border border-[#214a67] bg-[#08253c] p-4"><div className="mb-4 flex items-center justify-between"><p className="text-xs font-bold text-[#d8ebf8]">{title}</p><span className="text-[10px] text-[#7899af]">من البيانات الحية</span></div><div className="space-y-3">{rows.map((row) => <div key={row.key}><div className="mb-1.5 flex items-center justify-between gap-3 text-[11px]"><span className="text-[#a9c6d8]">{labels[row.key] ?? row.key}</span><span className="font-mono text-[#e5f4ff]">{row.count}{quantity && row.quantity !== undefined ? ` · ${new Intl.NumberFormat("ar-SA", { maximumFractionDigits: 3 }).format(row.quantity)} وحدة` : ""}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#12344f]"><div className="h-full rounded-full bg-[#2e92d0]" style={{ width: `${Math.max(row.count ? 8 : 0, (row.count / max) * 100)}%` }} /></div></div>)}</div></div>; }

export default function OperationalReportsPanel({ accessDenied, accessResolved }: { accessDenied: boolean; accessResolved: boolean }) {
  const { isAuthenticated } = useAuth();
  const summary = trpc.erp.reports.operationalSummary.useQuery(undefined, { enabled: isAuthenticated && accessResolved && !accessDenied, retry: false });
  const readiness = trpc.erp.financial.readiness.useQuery();
  const setupRequired = Boolean(summary.error?.message.includes("إكمال تهيئة الشركة"));
  const data = summary.data;

  return <div className="rounded-2xl border border-[#1c4563] bg-[#092238] shadow-[0_18px_42px_rgba(0,0,0,0.15)]">
    <div className="flex items-center gap-3 border-b border-[#193f5d] px-5 py-4"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#164563] text-[#83cdf6]"><BarChart3 className="h-4 w-4" /></div><div><h3 className="text-sm font-bold text-[#e6f2fc]">تقارير تشغيلية من البيانات المسجلة</h3><p className="mt-1 text-[10px] text-[#7899af]">مؤشرات تشغيلية حية للمستندات والمخزون والنقد والتدقيق؛ لا تعرض أرصدة أو نتائج أو قوائم مالية.</p></div></div>
    {summary.isLoading ? <div className="flex min-h-[250px] items-center justify-center gap-2 text-sm text-[#9ab9cf]"><Loader2 className="h-4 w-4 animate-spin" />جارٍ تجميع المؤشرات…</div> : setupRequired ? <Empty title="يلزم تهيئة الشركة أولًا" detail="تظهر المؤشرات عند ربط حسابك بنطاق شركة مصادق عليه." /> : summary.error ? <Empty title="تعذر تحميل المؤشرات" detail={summary.error.message} /> : data ? <div className="space-y-5 px-5 py-5">
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="المستندات التشغيلية" value={data.commercialDocuments.total} icon={<FileCheck2 className="h-4 w-4" />} /><Metric label="حركات المخزون" value={data.inventory.movementCount} icon={<Boxes className="h-4 w-4" />} /><Metric label="مواقع نشطة" value={data.inventory.activeLocationCount} icon={<Boxes className="h-4 w-4" />} /><Metric label="حسابات نقد نشطة" value={data.operations.activeCashAccountCount} icon={<CircleDollarSign className="h-4 w-4" />} /><Metric label="مسودات نقد غير مرحلة" value={data.cashDrafts.nonPostedCount} icon={<CircleDollarSign className="h-4 w-4" />} /><Metric label="قرارات تشغيلية" value={data.governance.operationalDecisionCount} icon={<ClipboardCheck className="h-4 w-4" />} /><Metric label="أدلة طباعة" value={data.governance.printEvidenceCount} icon={<FileCheck2 className="h-4 w-4" />} /><Metric label="أحداث تدقيق" value={data.governance.auditEventCount} icon={<History className="h-4 w-4" />} /></div>
      <div className="grid gap-4 xl:grid-cols-4"><Breakdown title="دورة المستندات" rows={data.commercialDocuments.byStatus} labels={documentStatusLabels} /><Breakdown title="أنواع المستندات" rows={data.commercialDocuments.byKind} labels={documentKindLabels} /><Breakdown title="اتجاهات حركات المخزون" rows={data.inventory.byDirection} labels={movementLabels} quantity /><Breakdown title="نوع مسودات النقد" rows={data.cashDrafts.byKind} labels={cashDraftKindLabels} /></div>
      <div className="grid gap-3 sm:grid-cols-3"><Metric label="مشاريع نشطة" value={data.operations.activeProjectCount} icon={<BarChart3 className="h-4 w-4" />} /><Metric label="موظفون نشطون" value={data.operations.activeEmployeeCount} icon={<UsersRound className="h-4 w-4" />} /><Metric label="جاهزية الدليل / الفترات" value={data.accountingReadiness.chartOfAccountsCount + data.accountingReadiness.accountingPeriodCount} icon={<LockKeyhole className="h-4 w-4" />} /></div>
      <p className="text-[10px] text-[#7899af]">آخر تجميع: {new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(data.generatedAt))} · لا تنتج هذه الشاشة أي قيود أو التزامات أو قرارات مالية.</p>
      <div className="flex items-start gap-3 rounded-xl border border-[#6e4738] bg-[#2d2023] p-4 text-xs leading-6 text-[#ffbeaf]"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="font-bold">القوائم والاعتماد المالي الرسميان غير متاحين</p><p>{readiness.data?.reason ?? "تستمر بوابة الجاهزية في منع الإصدار حتى تحقق الضوابط والأدلة."}</p></div></div>
    </div> : null}
  </div>;
}

function Empty({ title, detail }: { title: string; detail: string }) { return <div className="flex min-h-[250px] flex-col items-center justify-center px-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-xl border border-[#5b4a2e] bg-[#2d261c] text-[#edc56c]"><FileWarning className="h-5 w-5" /></div><h4 className="mt-3 text-sm font-bold text-[#f2dfad]">{title}</h4><p className="mt-1 max-w-sm text-xs leading-5 text-[#bcae89]">{detail}</p></div>; }
